package kanban.tasksAPI;

public enum Endpoint {
    GET_HISTORY,
    GET_ALL_TASKS,
    GET_STANDARD_TASKS,
    GET_EPIC_TASKS,
    GET_PRIORITIZED_TASKS,
    GET_FIND_TASK_BY_ID,
    POST_ADD_EPIC,
    POST_ADD_TASK,
    POST_CREATE_TASK,
    POST_CREATE_SUBTASK,
    POST_CREATE_EPIC,
    POST_UPDATE_TASK,
    POST_UPDATE_SUBTASK,
    POST_UPDATE_EPIC,
    POST_DELETE_TASK_BY_ID,
    POST_DELETE_ALL_TASKS,
    UNKNOWN
}
